### ISSUE TITLE
Set the User-Agent header

### ISSUE THREAD

**Issue by jdno** [rust-lang/infra-smoke-tests#37]
We should set the `User-Agent` header to a unique string that identifies this project so that we can more easily filter smoke tests in our request logs. This can be very useful when debugging problems.

We should set the `User-Agent` once globally and not in every test individually. This will require us to refactor how we currently initialize the HTTP clients. I suggest that we create our own `ClientBuilder` that wraps `reqwest::Client::builder()` and sets the `User-Agent`.

Depending on reqwest's API, it might be necessary for our own builder to accept and pass additional headers to the `default_headers`.

We can then refactor all usage of `reqwest::Client` to go through our own HTTP client.

**Comment by jannden** [comment]
I would like to give this issue a try. I got here from the Impl Room issues for EuroRust.
