### ISSUE TITLE
Parallelize test execution

### ISSUE THREAD

**Issue by jdno** [rust-lang/infra-smoke-tests#53]
Right now, the tests are executed sequentially. As the number of tests grows, executing the smoke tests sequentially will take longer and longer. Since the tests are self-contained, it is easy to execute them in parallel and avoid this slow increase in execution time.

We can achieve the best performance if we parallelize the execution on the test level. In this scenario, we initialize all tests and collect them into a single vector, which we can then really simply process in parallel. The downside is that we need to reorganize the tests into their test groups and suites after the execution, which will require changes to the data model (so that tests know their groups/suites) and the logic that prints the results.

A simpler implementation might be to parallelize each level of the hierarchy individually and recursively. So we would parallelize the execution of the test suites, and then each test suite would parallelize the execution of its own test groups, and each test group would run its tests in parallel. This makes collecting the results much simpler, since the current implementation does not need to change.

Given that the tests run asynchronously in a multi-threaded tokio runtime, the second option might actually end up achieving a similar level of performance as the first. We will just need to ensure that we don't block on and `.await` every test, but return futures that we can execute in parallel within each test group/suite.

**Comment by NULLx76** [comment]
I can have a look at this. I think I'd favour the second option, as it requires minimal code changes and should indeed still provide a significant enough speedup.
